package com.example.basecase.dataservice.databasebasicservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2021-11-04T20:16:36.729+08:00
 * Generated source version: 3.4.1
 *
 */
@WebServiceClient(name = "DatabaseBasicService",
                  wsdlLocation = "file:/C:/Users/kumin/Desktop/casebase_backend/webservice_CXF/caseBase_backEnd_service/src/main/resources/wsdl/dbBasicService.wsdl",
                  targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService")
public class DatabaseBasicService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://basecase.example.com/dataservice/DatabaseBasicService", "DatabaseBasicService");
    public final static QName DatabaseBasicServicePort = new QName("http://basecase.example.com/dataservice/DatabaseBasicService", "DatabaseBasicServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/kumin/Desktop/casebase_backend/webservice_CXF/caseBase_backEnd_service/src/main/resources/wsdl/dbBasicService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DatabaseBasicService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/kumin/Desktop/casebase_backend/webservice_CXF/caseBase_backEnd_service/src/main/resources/wsdl/dbBasicService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DatabaseBasicService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DatabaseBasicService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DatabaseBasicService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DatabaseBasicService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DatabaseBasicService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DatabaseBasicService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DatabaseBasicServicePort
     */
    @WebEndpoint(name = "DatabaseBasicServicePort")
    public DatabaseBasicServicePort getDatabaseBasicServicePort() {
        return super.getPort(DatabaseBasicServicePort, DatabaseBasicServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DatabaseBasicServicePort
     */
    @WebEndpoint(name = "DatabaseBasicServicePort")
    public DatabaseBasicServicePort getDatabaseBasicServicePort(WebServiceFeature... features) {
        return super.getPort(DatabaseBasicServicePort, DatabaseBasicServicePort.class, features);
    }

}
