package com.example.basecase.dataservice.databasebasicservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2021-11-04T20:16:36.712+08:00
 * Generated source version: 3.4.1
 *
 */
@WebService(targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", name = "DatabaseBasicServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface DatabaseBasicServicePort {

    @WebMethod
    @RequestWrapper(localName = "saveDoc", targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", className = "com.example.basecase.dataservice.databasebasicservice.SaveDoc")
    @ResponseWrapper(localName = "saveDocResponse", targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", className = "com.example.basecase.dataservice.databasebasicservice.SaveDocResponse")
    public void saveDoc(

        @WebParam(name = "doc", targetNamespace = "")
        Doc doc
    );

    @WebMethod
    @RequestWrapper(localName = "deleteDocByDocId", targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", className = "com.example.basecase.dataservice.databasebasicservice.DeleteDocByDocId")
    @ResponseWrapper(localName = "deleteDocByDocIdResponse", targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", className = "com.example.basecase.dataservice.databasebasicservice.DeleteDocByDocIdResponse")
    public void deleteDocByDocId(

        @WebParam(name = "docId", targetNamespace = "")
        Long docId
    );

    @WebMethod
    @RequestWrapper(localName = "findDocByDocId", targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", className = "com.example.basecase.dataservice.databasebasicservice.FindDocByDocId")
    @ResponseWrapper(localName = "findDocByDocIdResponse", targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", className = "com.example.basecase.dataservice.databasebasicservice.FindDocByDocIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Doc findDocByDocId(

        @WebParam(name = "docId", targetNamespace = "")
        Long docId
    );

    @WebMethod
    @RequestWrapper(localName = "queryPage", targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", className = "com.example.basecase.dataservice.databasebasicservice.QueryPage")
    @ResponseWrapper(localName = "queryPageResponse", targetNamespace = "http://basecase.example.com/dataservice/DatabaseBasicService", className = "com.example.basecase.dataservice.databasebasicservice.QueryPageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PageInfo queryPage(

        @WebParam(name = "arg0", targetNamespace = "")
        QueryBody arg0
    );
}
