package com.example.basecase.webservice.documentservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2021-11-11T22:24:13.163+08:00
 * Generated source version: 3.4.1
 *
 */
@WebServiceClient(name = "documentService",
                  wsdlLocation = "file:/C:/Users/kumin/Desktop/casebase_backend/webservice_CXF/caseBase_backEnd_client/src/main/resources/wsdl/document.wsdl",
                  targetNamespace = "http://basecase.example.com/webservice/DocumentService")
public class DocumentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://basecase.example.com/webservice/DocumentService", "documentService");
    public final static QName DocumentPortName = new QName("http://basecase.example.com/webservice/DocumentService", "documentPortName");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/kumin/Desktop/casebase_backend/webservice_CXF/caseBase_backEnd_client/src/main/resources/wsdl/document.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DocumentService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/kumin/Desktop/casebase_backend/webservice_CXF/caseBase_backEnd_client/src/main/resources/wsdl/document.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DocumentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DocumentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DocumentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DocumentPortType
     */
    @WebEndpoint(name = "documentPortName")
    public DocumentPortType getDocumentPortName() {
        return super.getPort(DocumentPortName, DocumentPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentPortType
     */
    @WebEndpoint(name = "documentPortName")
    public DocumentPortType getDocumentPortName(WebServiceFeature... features) {
        return super.getPort(DocumentPortName, DocumentPortType.class, features);
    }

}
